name: 🐛 Bug Report
description: Report a bug in the WebSocket Learning project
title: '[BUG] '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide detailed information to help us understand and fix the issue.

  - type: dropdown
    id: phase
    attributes:
      label: Learning Phase
      description: Which phase of the WebSocket learning project is affected?
      options:
        - Phase 1 (Basic Understanding)
        - Phase 2 (Implementation Technology)
        - Phase 3 (Testing & Evaluation)
        - Phase 4 (Production Development)
        - General/Infrastructure
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Bug Category
      description: What type of issue is this?
      options:
        - WebSocket Connection Issue
        - UI/UX Problem
        - Build/Deployment Issue
        - Documentation Error
        - Test Failure
        - Performance Issue
        - Browser Compatibility
        - TypeScript Error
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you encountered...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      placeholder: |
        - OS: [e.g. macOS 14.1, Windows 11, Ubuntu 22.04]
        - Browser: [e.g. Chrome 119, Firefox 119, Safari 17]
        - Node.js version: [e.g. 20.9.0]
        - npm version: [e.g. 10.1.0]
        - Project version/commit: [e.g. latest main, specific commit hash]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add console logs, error messages, or stack traces
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided detailed steps to reproduce the issue
          required: true
        - label: I have included relevant environment information
          required: true
        - label: I have checked the browser console for additional error information
          required: false
